### ISSUE TITLE
Add a high resolution image

### ISSUE THREAD

**Issue by Hector101** [fccIkeja/fccIkeja.github.io#4]
The image quality of the jumbotron container is too poor, so a high resolution image will be appreciated.

**Comment by vmengwa** [comment]
Yea. may be we could replace the image with any free stock images on the internet. We will take a nice picture in our next meetup.

**Comment by vmengwa** [comment]
![students-focused](https://cloud.githubusercontent.com/assets/17000899/16858969/d010c078-4a22-11e6-811d-a2f1571197bc.jpg)

**Comment by MrHeart** [comment]
ok guys, that's well noted.  I'll work on that now

**Comment by MrHeart** [comment]
the image is now changed on our site.
